import { useState } from "react";
import { useParams, useNavigate, Link } from "react-router";
import { ArrowLeft, ChevronLeft, ChevronRight, BookmarkPlus, Eye, Edit, Trash2, Archive, Star, Plus } from "lucide-react";
import { useAuth } from "../contexts/AuthContext";
import { MOCK_DESIGNS, MOCK_BOARDS, CATEGORY_LABELS, CATEGORY_COLORS } from "../data/mockData";

export function DesignDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { user } = useAuth();
  const isDesigner = user?.role === "designer";
  const [currentImageIndex, setCurrentImageIndex] = useState(0);
  const [addToBoardOpen, setAddToBoardOpen] = useState(false);
  const [deleteConfirmOpen, setDeleteConfirmOpen] = useState(false);
  const design = MOCK_DESIGNS.find((d) => d.id === id);
  if (!design) return (<div className="flex flex-col flex-1 items-center justify-center py-[96px]"><p className="body-body-16regular" style={{ color: "#17171999" }}>시안을 찾을 수 없습니다.</p><button onClick={() => navigate("/designs")} className="mt-[24px] flex items-center justify-center h-[44px] px-[24px] rounded-[8px] cursor-pointer" style={{ background: "#0066FF", color: "#fff" }}><span className="body-body-14mdeium">전체 시안으로</span></button></div>);
  const colors = CATEGORY_COLORS[design.category];
  return (
    <div className="flex flex-col flex-1 overflow-y-auto">
      <div className="flex items-center justify-between px-[24px] py-[14px] border-b sticky top-0 z-10" style={{ borderColor: "#EAEBEC", background: "#FFF" }}>
        <div className="flex items-center gap-[12px]"><Link to="/designs" className="flex items-center gap-[6px] body-body-14regular" style={{ color: "#17171999", textDecoration: "none" }}><ArrowLeft size={16} />전체 시안</Link><span style={{ color: "#EAEBEC" }}>/</span><span className="body-body-14regular" style={{ color: "#171719" }}>{design.title}</span></div>
        <div className="flex items-center gap-[8px]"><button onClick={() => setAddToBoardOpen(true)} className="flex items-center gap-[6px] h-[36px] px-[14px] rounded-[8px] cursor-pointer" style={{ background: "#EBF3FF", color: "#0066FF" }}><BookmarkPlus size={15} /><span className="body-body-14mdeium">보드에 추가</span></button>{isDesigner && (<><button className="flex items-center gap-[6px] h-[36px] px-[14px] rounded-[8px] cursor-pointer border" style={{ borderColor: "#EAEBEC", background: "#FFF", color: "#171719" }}><Edit size={15} /><span className="body-body-14mdeium">수정</span></button><button className="flex items-center gap-[6px] h-[36px] px-[14px] rounded-[8px] cursor-pointer border" style={{ borderColor: "#EAEBEC", background: "#FFF", color: "#17171999" }}><Archive size={15} /><span className="body-body-14mdeium">보관</span></button><button onClick={() => setDeleteConfirmOpen(true)} className="flex items-center gap-[6px] h-[36px] px-[14px] rounded-[8px] cursor-pointer" style={{ background: "#FEF0EF", color: "#FF3B30" }}><Trash2 size={15} /><span className="body-body-14mdeium">삭제</span></button></>)}</div>
      </div>
      <div className="flex flex-col lg:flex-row gap-[32px] p-[32px] max-w-[1200px] mx-auto w-full">
        <div className="flex flex-col gap-[16px] flex-1">
          <div className="relative w-full rounded-[12px] overflow-hidden" style={{ background: "#F7F7F8" }}><img src={design.images[currentImageIndex]} alt={`${design.title} ${currentImageIndex + 1}`} className="w-full object-cover" style={{ height: 440 }} />{design.images.length > 1 && (<><button onClick={() => setCurrentImageIndex(Math.max(0, currentImageIndex - 1))} disabled={currentImageIndex === 0} className="absolute left-[16px] top-1/2 -translate-y-1/2 flex items-center justify-center w-[40px] h-[40px] rounded-full cursor-pointer" style={{ background: "rgba(255,255,255,0.9)", opacity: currentImageIndex === 0 ? 0.4 : 1 }}><ChevronLeft size={20} style={{ color: "#171719" }} /></button><button onClick={() => setCurrentImageIndex(Math.min(design.images.length - 1, currentImageIndex + 1))} disabled={currentImageIndex === design.images.length - 1} className="absolute right-[16px] top-1/2 -translate-y-1/2 flex items-center justify-center w-[40px] h-[40px] rounded-full cursor-pointer" style={{ background: "rgba(255,255,255,0.9)", opacity: currentImageIndex === design.images.length - 1 ? 0.4 : 1 }}><ChevronRight size={20} style={{ color: "#171719" }} /></button></>)}</div>
          {design.images.length > 1 && (<div className="flex gap-[8px]">{design.images.map((img, i) => (<button key={i} onClick={() => setCurrentImageIndex(i)} className="rounded-[8px] overflow-hidden cursor-pointer flex-shrink-0" style={{ width: 80, height: 56, border: `2px solid ${i === currentImageIndex ? "#0066FF" : "#EAEBEC"}` }}><img src={img} alt="" className="w-full h-full object-cover" /></button>))}</div>)}
        </div>
        <div className="flex flex-col gap-[24px]" style={{ width: 320, flexShrink: 0 }}>
          <div className="flex flex-col gap-[12px]"><div className="flex items-center gap-[8px]"><span className="body-body-12medium px-[8px] py-[2px] rounded-[4px]" style={{ background: colors.bg, color: colors.text }}>{CATEGORY_LABELS[design.category]}</span>{design.isRepresentative && (<span className="flex items-center gap-[4px] body-body-12medium px-[8px] py-[2px] rounded-[4px]" style={{ background: "#FFF8E6", color: "#FF9500" }}><Star size={10} fill="#FF9500" />대표 사례</span>)}</div><h1 className="heading-heading-24bold" style={{ color: "#171719" }}>{design.title}</h1><p className="body-body-14regular" style={{ color: "#17171999" }}>{design.description}</p></div>
          <div className="flex items-center gap-[16px] p-[16px] rounded-[10px]" style={{ background: "#F7F7F8" }}><div className="flex items-center gap-[6px]"><Eye size={14} style={{ color: "#17171973" }} /><span className="body-body-14regular" style={{ color: "#17171999" }}>조회 {design.viewCount}회</span></div></div>
          <div className="flex flex-col gap-[16px]">{[{ label: "기업명", value: design.company }, { label: "산업분야", value: design.industry }, { label: "구축연도", value: `${design.year}년` }].map((item) => (<div key={item.label} className="flex items-start"><span className="body-body-14regular shrink-0" style={{ color: "#17171973", width: 80 }}>{item.label}</span><span className="body-body-14regular" style={{ color: "#171719" }}>{item.value}</span></div>))}<div className="flex items-start"><span className="body-body-14regular shrink-0" style={{ color: "#17171973", width: 80 }}>화면 유형</span><div className="flex flex-wrap gap-[4px]">{design.screenTypes.map((s) => (<span key={s} className="body-body-12regular px-[8px] py-[3px] rounded-[4px]" style={{ background: "#F7F7F8", color: "#171719" }}>{s}</span>))}</div></div><div className="flex items-start"><span className="body-body-14regular shrink-0" style={{ color: "#17171973", width: 80 }}>디바이스</span><div className="flex flex-wrap gap-[4px]">{design.devices.map((d) => (<span key={d} className="body-body-12regular px-[8px] py-[3px] rounded-[4px]" style={{ background: "#F7F7F8", color: "#171719" }}>{d}</span>))}</div></div><div className="flex items-start"><span className="body-body-14regular shrink-0" style={{ color: "#17171973", width: 80 }}>태그</span><div className="flex flex-wrap gap-[4px]">{design.tags.map((tag) => (<span key={tag} className="body-body-12regular px-[8px] py-[3px] rounded-[4px]" style={{ background: "#EAEBEC", color: "#17171999" }}>#{tag}</span>))}</div></div></div>
          {isDesigner && (<div className="flex items-center justify-between p-[14px] rounded-[8px]" style={{ background: design.isRepresentative ? "#FFF8E6" : "#F7F7F8", border: "1px solid #EAEBEC" }}><div className="flex flex-col gap-[2px]"><span className="body-body-14mdeium" style={{ color: "#171719" }}>대표 사례 설정</span><span className="body-body-12regular" style={{ color: "#17171973" }}>퍼블릭 고객 사례 페이지에 노출됩니다.</span></div><div className="relative cursor-pointer" style={{ width: 44, height: 24 }}><div className="absolute inset-0 rounded-full transition-colors" style={{ background: design.isRepresentative ? "#0066FF" : "#EAEBEC" }} /><div className="absolute top-[2px] rounded-full" style={{ width: 20, height: 20, background: "#FFF", left: design.isRepresentative ? 22 : 2, transition: "left 0.2s", boxShadow: "0 1px 4px rgba(0,0,0,0.15)" }} /></div></div>)}
          <button onClick={() => setAddToBoardOpen(true)} className="flex items-center justify-center gap-[8px] h-[48px] rounded-[8px] cursor-pointer" style={{ background: "#0066FF", color: "#fff" }}><BookmarkPlus size={18} /><span className="body-body-16medium">레퍼런스 보드에 추가</span></button>
        </div>
      </div>
      {addToBoardOpen && (<div className="fixed inset-0 z-50 flex items-center justify-center p-[24px]" style={{ background: "rgba(0,0,0,0.4)" }} onClick={(e) => { if (e.target === e.currentTarget) setAddToBoardOpen(false); }}><div className="w-full max-w-[400px] rounded-[16px] p-[32px] flex flex-col gap-[20px]" style={{ background: "#FFF" }}><div className="flex flex-col gap-[6px]"><h2 className="heading-heading-20bold" style={{ color: "#171719" }}>레퍼런스 보드에 추가</h2><p className="body-body-14regular" style={{ color: "#17171999" }}>추가할 보드를 선택하세요.</p></div><div className="flex flex-col gap-[8px]">{MOCK_BOARDS.map((board) => (<button key={board.id} onClick={() => setAddToBoardOpen(false)} className="flex items-center justify-between w-full h-[52px] px-[16px] rounded-[8px] cursor-pointer border transition-all" style={{ borderColor: "#EAEBEC", background: "#FFF" }} onMouseEnter={(e) => { e.currentTarget.style.borderColor = "#0066FF"; e.currentTarget.style.background = "#F5F9FF"; }} onMouseLeave={(e) => { e.currentTarget.style.borderColor = "#EAEBEC"; e.currentTarget.style.background = "#FFF"; }}><div className="flex flex-col items-start"><span className="body-body-14mdeium" style={{ color: "#171719" }}>{board.title}</span><span className="body-body-12regular" style={{ color: "#17171973" }}>{board.clientName} · {board.items.length}개</span></div><BookmarkPlus size={16} style={{ color: "#17171999" }} /></button>))}<button onClick={() => setAddToBoardOpen(false)} className="flex items-center justify-center gap-[8px] w-full h-[52px] rounded-[8px] cursor-pointer border" style={{ borderColor: "#EAEBEC", borderStyle: "dashed", background: "#F7F7F8", color: "#17171999" }}><Plus size={16} /><span className="body-body-14mdeium">새 보드 만들기</span></button></div><button onClick={() => setAddToBoardOpen(false)} className="flex items-center justify-center h-[44px] rounded-[8px] cursor-pointer border" style={{ borderColor: "#EAEBEC", background: "#FFF", color: "#171719" }}><span className="body-body-14mdeium">취소</span></button></div></div>)}
      {deleteConfirmOpen && (<div className="fixed inset-0 z-50 flex items-center justify-center p-[24px]" style={{ background: "rgba(0,0,0,0.4)" }} onClick={(e) => { if (e.target === e.currentTarget) setDeleteConfirmOpen(false); }}><div className="w-full max-w-[380px] rounded-[16px] p-[32px] flex flex-col gap-[20px]" style={{ background: "#FFF" }}><div className="flex flex-col gap-[8px]"><h2 className="heading-heading-20bold" style={{ color: "#171719" }}>시안을 삭제하시겠습니까?</h2><p className="body-body-14regular" style={{ color: "#17171999" }}>삭제한 시안은 복구할 수 없습니다. 레퍼런스 보드에 추가된 항목도 함께 제거됩니다.</p></div><div className="flex items-center gap-[8px]"><button onClick={() => setDeleteConfirmOpen(false)} className="flex-1 h-[44px] rounded-[8px] cursor-pointer border" style={{ borderColor: "#EAEBEC", background: "#FFF", color: "#171719" }}><span className="body-body-14mdeium">취소</span></button><button onClick={() => { setDeleteConfirmOpen(false); navigate("/designs"); }} className="flex-1 h-[44px] rounded-[8px] cursor-pointer" style={{ background: "#FF3B30", color: "#fff" }}><span className="body-body-14mdeium">삭제</span></button></div></div></div>)}
    </div>
  );
}
